version: '3'

services:
  postgres:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_USER: camel
      POSTGRES_PASSWORD: camel
    ports:
      - "5432:5432"

  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
