version: '3.8'

services:
  sftp:
    image: atmoz/sftp
    volumes:
      - ./sftp-data:/home/foo/upload
    ports:
      - "2222:22"
    command: foo:pass:::upload

  postgres:
    image: postgres
    container_name: postgres_db
    depends_on:
      - sftp
    environment:
      POSTGRES_USER: camel
      POSTGRES_PASSWORD: camel
    ports:
      - "5432:5432"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d/

  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      SFTP_HOST: sftp
      SFTP_PORT: 22
      SFTP_USER: foo
      SFTP_PASSWORD: pass
