CREATE TABLE  customer_payments (
    id SERIAL PRIMARY KEY,
    limit_bal DECIMAL,
    sex INTEGER,
    education INTEGER,
    marriage INTEGER,
    age INTEGER,
    pay0 DECIMAL,
    pay2 DECIMAL,
    pay3 DECIMAL,
    pay4 DECIMAL,
    pay5 DECIMAL,
    pay6 DECIMAL,
    bill_amt1 DECIMAL,
    bill_amt2 DECIMAL,
    bill_amt3 DECIMAL,
    bill_amt4 DECIMAL,
    bill_amt5 DECIMAL,
    bill_amt6 DECIMAL,
    pay_amt1 DECIMAL,
    pay_amt2 DECIMAL,
    pay_amt3 DECIMAL,
    pay_amt4 DECIMAL,
    pay_amt5 DECIMAL,
    pay_amt6 DECIMAL,
    default_payment_next_month INTEGER
);
